logging:
  level: INFO
  file: pcr_pipeline.log
settings:
  enable_warehouse: false

directories:
  base_dir: E:\SM_Integration\Instrument_to_LIMS\PCR_data 
  raw_dir: input
  processed_dir: input/processed
  warehouse_dir: warehouse
  analysis_dir: analysis_files/new
  lims_import_dir: lims_import_files/input
  error_dir: input/error
  log_dir: logfiles

required_meta_keys:
  - file_name
  - instrument_type
  - block_type
  - run_end_time
  - instrument_serial_number

required_df_cols:
  - well
  - well position
  - sample name
  - test number
  - target name
  - reporter
  - ct threshold
  - baseline start
  - baseline end
  - ct

meta_key_map:
  File Name: file_name
  Experiment File Name: file_name
  Instrument Type: instrument_type
  Instrument Type=: instrument_type
  Block Type: block_type
  Experiment Run End Time: run_end_time
  Run End Data/Time: run_end_time
  Instrument Serial Number: instrument_serial_number

instrument_key_map:
  '2778622100020': E163
  '278860668': E95
  '278880932': E50
  '2778725070009': E187

poll_interval_seconds: 5
